name: Build and push images

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      PR_NUMBER: ${{ github.event.number }}
      PR_HEAD_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1

      - name: Build checks with nix-fast-build
        run: |
          nix shell --inputs-from . nixpkgs#nix-fast-build -c \
            nix-fast-build --no-nom --max-jobs 3 --eval-workers 3 --eval-max-memory-size 4096 \
            --option accept-flake-config false --option eval-cache false --flake '.#checks.x86_64-linux'

      - name: Push images
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          REGISTRY_AUTH_FILE: ${{ runner.temp }}/containers-auth.json
          DOCKER_CONFIG: ${{ runner.temp }}/docker-config
        run: ./result-pushImages/bin/push-images
